/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'shops-and-services': ShopsAndService;
    gastronomy: Gastronomy;
    events: Event;
    gallery: Gallery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'shops-and-services': ShopsAndServicesSelect<false> | ShopsAndServicesSelect<true>;
    gastronomy: GastronomySelect<false> | GastronomySelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    footer: Footer;
    contact: Contact;
    'events-page': EventsPage;
    'gastronomy-page': GastronomyPage;
    'shops-and-services-page': ShopsAndServicesPage;
    'general-settings': GeneralSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'gastronomy-page': GastronomyPageSelect<false> | GastronomyPageSelect<true>;
    'shops-and-services-page': ShopsAndServicesPageSelect<false> | ShopsAndServicesPageSelect<true>;
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops-and-services".
 */
export interface ShopsAndService {
  id: string;
  image: string | Media;
  name: string;
  /**
   * Exemplo: Moda jovem
   */
  category: string;
  /**
   * Exemplo: Sala 17
   */
  room: string;
  openingHours: {
    /**
     * Exemplo: 08:30 às 19h
     */
    weekdays: string;
    /**
     * Exemplo: 08:30 às 18h
     */
    saturday: string;
  };
  /**
   * Exemplo: 54 3401 5982
   */
  phone: string;
  socialLinks: {
    network: 'instagram' | 'whatsapp' | 'facebook';
    url: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastronomy".
 */
export interface Gastronomy {
  id: string;
  image: string | Media;
  name: string;
  /**
   * Exemplo: Moda jovem
   */
  category: string;
  /**
   * Exemplo: Sala 17
   */
  room: string;
  openingHours: {
    /**
     * Exemplo: 08:30 às 19h
     */
    weekdays: string;
    /**
     * Exemplo: 08:30 às 18h
     */
    saturday: string;
  };
  /**
   * Exemplo: 54 3401 5982
   */
  phone: string;
  socialLinks: {
    network: 'instagram' | 'whatsapp' | 'facebook';
    url: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  image: string | Media;
  /**
   * Exemplo: Participe da Estação Bem-estar
   */
  title: string;
  date: string;
  /**
   * Exemplo: 9h
   */
  startTime: string;
  /**
   * Exemplo: 13h
   */
  endTime: string;
  /**
   * Exemplo: Uma manhã para cuidar de você no Boulevard Garibaldi
   */
  description: string;
  cta: {
    label: string;
    url: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  image: string | Media;
  /**
   * Texto opcional exibido sobre a imagem.
   */
  title?: string | null;
  date?: string | null;
  /**
   * Texto opcional exibido sobre a imagem.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'shops-and-services';
        value: string | ShopsAndService;
      } | null)
    | ({
        relationTo: 'gastronomy';
        value: string | Gastronomy;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops-and-services_select".
 */
export interface ShopsAndServicesSelect<T extends boolean = true> {
  image?: T;
  name?: T;
  category?: T;
  room?: T;
  openingHours?:
    | T
    | {
        weekdays?: T;
        saturday?: T;
      };
  phone?: T;
  socialLinks?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastronomy_select".
 */
export interface GastronomySelect<T extends boolean = true> {
  image?: T;
  name?: T;
  category?: T;
  room?: T;
  openingHours?:
    | T
    | {
        weekdays?: T;
        saturday?: T;
      };
  phone?: T;
  socialLinks?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  description?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  title?: T;
  date?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero?: {
    slides?:
      | {
          image?: (string | null) | Media;
          /**
           * Imagem para dispositivos móveis (tamanho: 375x667)
           */
          imageMobile?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  section: {
    /**
     * Imagem para dispositivos móveis (tamanho: 750x750)
     */
    image?: (string | null) | Media;
    title: string;
    description: string;
    items?:
      | {
          icon?: (string | null) | Media;
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  banner: {
    image?: (string | null) | Media;
    title: string;
    cta: string;
    ctaLink: string;
  };
  seo: {
    /**
     * Título usado em mecanismos de busca e compartilhamentos.
     */
    title: string;
    /**
     * Descrição usada em mecanismos de busca e compartilhamentos.
     */
    description: string;
    image?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  brand: {
    logo: string | Media;
    address: string;
  };
  openingHours: {
    title: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  contacts: {
    title: string;
    items?:
      | {
          name: string;
          phone: string;
          email: string;
          id?: string | null;
        }[]
      | null;
  };
  social: {
    title: string;
    links?:
      | {
          network: 'instagram' | 'facebook';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  arrival: {
    breadcrumbLabel: string;
    title: string;
    description: string;
    /**
     * URL do Google Maps usada para exibir o mapa na página e abrir a localização.
     */
    mapUrl: string;
  };
  contactForm: {
    title: string;
    description: string;
    backgroundImage?: (string | null) | Media;
  };
  seo: {
    /**
     * Título usado em mecanismos de busca e compartilhamentos.
     */
    title: string;
    /**
     * Descrição usada em mecanismos de busca e compartilhamentos.
     */
    description: string;
    image?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: string;
  title: string;
  description: string;
  textPrimary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Ese texto será exibido na página Home (seção de eventos).
   */
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo: {
    /**
     * Título usado em mecanismos de busca e compartilhamentos.
     */
    title: string;
    /**
     * Descrição usada em mecanismos de busca e compartilhamentos.
     */
    description: string;
    image?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastronomy-page".
 */
export interface GastronomyPage {
  id: string;
  background: string | Media;
  description: string;
  group: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  seo: {
    /**
     * Título usado em mecanismos de busca e compartilhamentos.
     */
    title: string;
    /**
     * Descrição usada em mecanismos de busca e compartilhamentos.
     */
    description: string;
    image?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops-and-services-page".
 */
export interface ShopsAndServicesPage {
  id: string;
  background: string | Media;
  description: string;
  group: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  seo: {
    /**
     * Título usado em mecanismos de busca e compartilhamentos.
     */
    title: string;
    /**
     * Descrição usada em mecanismos de busca e compartilhamentos.
     */
    description: string;
    image?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: string;
  whatsapp: {
    enabled?: boolean | null;
    /**
     * Use DDI + DDD + número, somente dígitos. Ex: 5551999999999
     */
    phone: string;
    /**
     * Mensagem opcional que será preenchida ao abrir o WhatsApp.
     */
    message?: string | null;
  };
  contactForm: {
    recipientEmail: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        slides?:
          | T
          | {
              image?: T;
              imageMobile?: T;
              id?: T;
            };
      };
  section?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              id?: T;
            };
      };
  banner?:
    | T
    | {
        image?: T;
        title?: T;
        cta?: T;
        ctaLink?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        logo?: T;
        address?: T;
      };
  openingHours?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  contacts?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              name?: T;
              phone?: T;
              email?: T;
              id?: T;
            };
      };
  social?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              network?: T;
              url?: T;
              id?: T;
            };
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  arrival?:
    | T
    | {
        breadcrumbLabel?: T;
        title?: T;
        description?: T;
        mapUrl?: T;
      };
  contactForm?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundImage?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  textPrimary?: T;
  text?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastronomy-page_select".
 */
export interface GastronomyPageSelect<T extends boolean = true> {
  background?: T;
  description?: T;
  group?:
    | T
    | {
        title?: T;
        description?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops-and-services-page_select".
 */
export interface ShopsAndServicesPageSelect<T extends boolean = true> {
  background?: T;
  description?: T;
  group?:
    | T
    | {
        title?: T;
        description?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  whatsapp?:
    | T
    | {
        enabled?: T;
        phone?: T;
        message?: T;
      };
  contactForm?:
    | T
    | {
        recipientEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}